// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mesos/authentication/authentication.proto

#ifndef PROTOBUF_mesos_2fauthentication_2fauthentication_2eproto__INCLUDED
#define PROTOBUF_mesos_2fauthentication_2fauthentication_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_mesos_2fauthentication_2fauthentication_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsAuthenticateMessageImpl();
void InitDefaultsAuthenticateMessage();
void InitDefaultsAuthenticationMechanismsMessageImpl();
void InitDefaultsAuthenticationMechanismsMessage();
void InitDefaultsAuthenticationStartMessageImpl();
void InitDefaultsAuthenticationStartMessage();
void InitDefaultsAuthenticationStepMessageImpl();
void InitDefaultsAuthenticationStepMessage();
void InitDefaultsAuthenticationCompletedMessageImpl();
void InitDefaultsAuthenticationCompletedMessage();
void InitDefaultsAuthenticationFailedMessageImpl();
void InitDefaultsAuthenticationFailedMessage();
void InitDefaultsAuthenticationErrorMessageImpl();
void InitDefaultsAuthenticationErrorMessage();
inline void InitDefaults() {
  InitDefaultsAuthenticateMessage();
  InitDefaultsAuthenticationMechanismsMessage();
  InitDefaultsAuthenticationStartMessage();
  InitDefaultsAuthenticationStepMessage();
  InitDefaultsAuthenticationCompletedMessage();
  InitDefaultsAuthenticationFailedMessage();
  InitDefaultsAuthenticationErrorMessage();
}
}  // namespace protobuf_mesos_2fauthentication_2fauthentication_2eproto
namespace mesos {
namespace internal {
class AuthenticateMessage;
class AuthenticateMessageDefaultTypeInternal;
extern AuthenticateMessageDefaultTypeInternal _AuthenticateMessage_default_instance_;
class AuthenticationCompletedMessage;
class AuthenticationCompletedMessageDefaultTypeInternal;
extern AuthenticationCompletedMessageDefaultTypeInternal _AuthenticationCompletedMessage_default_instance_;
class AuthenticationErrorMessage;
class AuthenticationErrorMessageDefaultTypeInternal;
extern AuthenticationErrorMessageDefaultTypeInternal _AuthenticationErrorMessage_default_instance_;
class AuthenticationFailedMessage;
class AuthenticationFailedMessageDefaultTypeInternal;
extern AuthenticationFailedMessageDefaultTypeInternal _AuthenticationFailedMessage_default_instance_;
class AuthenticationMechanismsMessage;
class AuthenticationMechanismsMessageDefaultTypeInternal;
extern AuthenticationMechanismsMessageDefaultTypeInternal _AuthenticationMechanismsMessage_default_instance_;
class AuthenticationStartMessage;
class AuthenticationStartMessageDefaultTypeInternal;
extern AuthenticationStartMessageDefaultTypeInternal _AuthenticationStartMessage_default_instance_;
class AuthenticationStepMessage;
class AuthenticationStepMessageDefaultTypeInternal;
extern AuthenticationStepMessageDefaultTypeInternal _AuthenticationStepMessage_default_instance_;
}  // namespace internal
}  // namespace mesos
namespace mesos {
namespace internal {

// ===================================================================

class AuthenticateMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticateMessage) */ {
 public:
  AuthenticateMessage();
  virtual ~AuthenticateMessage();

  AuthenticateMessage(const AuthenticateMessage& from);

  inline AuthenticateMessage& operator=(const AuthenticateMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticateMessage(AuthenticateMessage&& from) noexcept
    : AuthenticateMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticateMessage& operator=(AuthenticateMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticateMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticateMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticateMessage*>(
               &_AuthenticateMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(AuthenticateMessage* other);
  void Swap(AuthenticateMessage* other);
  friend void swap(AuthenticateMessage& a, AuthenticateMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticateMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticateMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticateMessage& from);
  void MergeFrom(const AuthenticateMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticateMessage* other);
  protected:
  explicit AuthenticateMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string pid = 1;
  bool has_pid() const;
  void clear_pid();
  static const int kPidFieldNumber = 1;
  const ::std::string& pid() const;
  void set_pid(const ::std::string& value);
  #if LANG_CXX11
  void set_pid(::std::string&& value);
  #endif
  void set_pid(const char* value);
  void set_pid(const char* value, size_t size);
  ::std::string* mutable_pid();
  ::std::string* release_pid();
  void set_allocated_pid(::std::string* pid);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_pid();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_pid(
      ::std::string* pid);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticateMessage)
 private:
  void set_has_pid();
  void clear_has_pid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr pid_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticateMessageImpl();
};
// -------------------------------------------------------------------

class AuthenticationMechanismsMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticationMechanismsMessage) */ {
 public:
  AuthenticationMechanismsMessage();
  virtual ~AuthenticationMechanismsMessage();

  AuthenticationMechanismsMessage(const AuthenticationMechanismsMessage& from);

  inline AuthenticationMechanismsMessage& operator=(const AuthenticationMechanismsMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationMechanismsMessage(AuthenticationMechanismsMessage&& from) noexcept
    : AuthenticationMechanismsMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticationMechanismsMessage& operator=(AuthenticationMechanismsMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationMechanismsMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationMechanismsMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticationMechanismsMessage*>(
               &_AuthenticationMechanismsMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(AuthenticationMechanismsMessage* other);
  void Swap(AuthenticationMechanismsMessage* other);
  friend void swap(AuthenticationMechanismsMessage& a, AuthenticationMechanismsMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationMechanismsMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationMechanismsMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationMechanismsMessage& from);
  void MergeFrom(const AuthenticationMechanismsMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationMechanismsMessage* other);
  protected:
  explicit AuthenticationMechanismsMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string mechanisms = 1;
  int mechanisms_size() const;
  void clear_mechanisms();
  static const int kMechanismsFieldNumber = 1;
  const ::std::string& mechanisms(int index) const;
  ::std::string* mutable_mechanisms(int index);
  void set_mechanisms(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_mechanisms(int index, ::std::string&& value);
  #endif
  void set_mechanisms(int index, const char* value);
  void set_mechanisms(int index, const char* value, size_t size);
  ::std::string* add_mechanisms();
  void add_mechanisms(const ::std::string& value);
  #if LANG_CXX11
  void add_mechanisms(::std::string&& value);
  #endif
  void add_mechanisms(const char* value);
  void add_mechanisms(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& mechanisms() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_mechanisms();

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationMechanismsMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> mechanisms_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticationMechanismsMessageImpl();
};
// -------------------------------------------------------------------

class AuthenticationStartMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticationStartMessage) */ {
 public:
  AuthenticationStartMessage();
  virtual ~AuthenticationStartMessage();

  AuthenticationStartMessage(const AuthenticationStartMessage& from);

  inline AuthenticationStartMessage& operator=(const AuthenticationStartMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationStartMessage(AuthenticationStartMessage&& from) noexcept
    : AuthenticationStartMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticationStartMessage& operator=(AuthenticationStartMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationStartMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationStartMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticationStartMessage*>(
               &_AuthenticationStartMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void UnsafeArenaSwap(AuthenticationStartMessage* other);
  void Swap(AuthenticationStartMessage* other);
  friend void swap(AuthenticationStartMessage& a, AuthenticationStartMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationStartMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationStartMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationStartMessage& from);
  void MergeFrom(const AuthenticationStartMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationStartMessage* other);
  protected:
  explicit AuthenticationStartMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mechanism = 1;
  bool has_mechanism() const;
  void clear_mechanism();
  static const int kMechanismFieldNumber = 1;
  const ::std::string& mechanism() const;
  void set_mechanism(const ::std::string& value);
  #if LANG_CXX11
  void set_mechanism(::std::string&& value);
  #endif
  void set_mechanism(const char* value);
  void set_mechanism(const char* value, size_t size);
  ::std::string* mutable_mechanism();
  ::std::string* release_mechanism();
  void set_allocated_mechanism(::std::string* mechanism);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_mechanism();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_mechanism(
      ::std::string* mechanism);

  // optional bytes data = 2;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_data();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      ::std::string* data);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationStartMessage)
 private:
  void set_has_mechanism();
  void clear_has_mechanism();
  void set_has_data();
  void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr mechanism_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticationStartMessageImpl();
};
// -------------------------------------------------------------------

class AuthenticationStepMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticationStepMessage) */ {
 public:
  AuthenticationStepMessage();
  virtual ~AuthenticationStepMessage();

  AuthenticationStepMessage(const AuthenticationStepMessage& from);

  inline AuthenticationStepMessage& operator=(const AuthenticationStepMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationStepMessage(AuthenticationStepMessage&& from) noexcept
    : AuthenticationStepMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticationStepMessage& operator=(AuthenticationStepMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationStepMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationStepMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticationStepMessage*>(
               &_AuthenticationStepMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void UnsafeArenaSwap(AuthenticationStepMessage* other);
  void Swap(AuthenticationStepMessage* other);
  friend void swap(AuthenticationStepMessage& a, AuthenticationStepMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationStepMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationStepMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationStepMessage& from);
  void MergeFrom(const AuthenticationStepMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationStepMessage* other);
  protected:
  explicit AuthenticationStepMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes data = 1;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_data();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      ::std::string* data);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationStepMessage)
 private:
  void set_has_data();
  void clear_has_data();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticationStepMessageImpl();
};
// -------------------------------------------------------------------

class AuthenticationCompletedMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticationCompletedMessage) */ {
 public:
  AuthenticationCompletedMessage();
  virtual ~AuthenticationCompletedMessage();

  AuthenticationCompletedMessage(const AuthenticationCompletedMessage& from);

  inline AuthenticationCompletedMessage& operator=(const AuthenticationCompletedMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationCompletedMessage(AuthenticationCompletedMessage&& from) noexcept
    : AuthenticationCompletedMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticationCompletedMessage& operator=(AuthenticationCompletedMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationCompletedMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationCompletedMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticationCompletedMessage*>(
               &_AuthenticationCompletedMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void UnsafeArenaSwap(AuthenticationCompletedMessage* other);
  void Swap(AuthenticationCompletedMessage* other);
  friend void swap(AuthenticationCompletedMessage& a, AuthenticationCompletedMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationCompletedMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationCompletedMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationCompletedMessage& from);
  void MergeFrom(const AuthenticationCompletedMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationCompletedMessage* other);
  protected:
  explicit AuthenticationCompletedMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationCompletedMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticationCompletedMessageImpl();
};
// -------------------------------------------------------------------

class AuthenticationFailedMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticationFailedMessage) */ {
 public:
  AuthenticationFailedMessage();
  virtual ~AuthenticationFailedMessage();

  AuthenticationFailedMessage(const AuthenticationFailedMessage& from);

  inline AuthenticationFailedMessage& operator=(const AuthenticationFailedMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationFailedMessage(AuthenticationFailedMessage&& from) noexcept
    : AuthenticationFailedMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticationFailedMessage& operator=(AuthenticationFailedMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationFailedMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationFailedMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticationFailedMessage*>(
               &_AuthenticationFailedMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void UnsafeArenaSwap(AuthenticationFailedMessage* other);
  void Swap(AuthenticationFailedMessage* other);
  friend void swap(AuthenticationFailedMessage& a, AuthenticationFailedMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationFailedMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationFailedMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationFailedMessage& from);
  void MergeFrom(const AuthenticationFailedMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationFailedMessage* other);
  protected:
  explicit AuthenticationFailedMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationFailedMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticationFailedMessageImpl();
};
// -------------------------------------------------------------------

class AuthenticationErrorMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mesos.internal.AuthenticationErrorMessage) */ {
 public:
  AuthenticationErrorMessage();
  virtual ~AuthenticationErrorMessage();

  AuthenticationErrorMessage(const AuthenticationErrorMessage& from);

  inline AuthenticationErrorMessage& operator=(const AuthenticationErrorMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AuthenticationErrorMessage(AuthenticationErrorMessage&& from) noexcept
    : AuthenticationErrorMessage() {
    *this = ::std::move(from);
  }

  inline AuthenticationErrorMessage& operator=(AuthenticationErrorMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationErrorMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AuthenticationErrorMessage* internal_default_instance() {
    return reinterpret_cast<const AuthenticationErrorMessage*>(
               &_AuthenticationErrorMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void UnsafeArenaSwap(AuthenticationErrorMessage* other);
  void Swap(AuthenticationErrorMessage* other);
  friend void swap(AuthenticationErrorMessage& a, AuthenticationErrorMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AuthenticationErrorMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  AuthenticationErrorMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AuthenticationErrorMessage& from);
  void MergeFrom(const AuthenticationErrorMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AuthenticationErrorMessage* other);
  protected:
  explicit AuthenticationErrorMessage(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string error = 1;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_error();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error(
      ::std::string* error);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationErrorMessage)
 private:
  void set_has_error();
  void clear_has_error();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  friend struct ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::TableStruct;
  friend void ::protobuf_mesos_2fauthentication_2fauthentication_2eproto::InitDefaultsAuthenticationErrorMessageImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AuthenticateMessage

// required string pid = 1;
inline bool AuthenticateMessage::has_pid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticateMessage::set_has_pid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticateMessage::clear_has_pid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticateMessage::clear_pid() {
  pid_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  clear_has_pid();
}
inline const ::std::string& AuthenticateMessage::pid() const {
  // @@protoc_insertion_point(field_get:mesos.internal.AuthenticateMessage.pid)
  return pid_.Get();
}
inline void AuthenticateMessage::set_pid(const ::std::string& value) {
  set_has_pid();
  pid_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticateMessage.pid)
}
#if LANG_CXX11
inline void AuthenticateMessage::set_pid(::std::string&& value) {
  set_has_pid();
  pid_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:mesos.internal.AuthenticateMessage.pid)
}
#endif
inline void AuthenticateMessage::set_pid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_pid();
  pid_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:mesos.internal.AuthenticateMessage.pid)
}
inline void AuthenticateMessage::set_pid(const char* value,
    size_t size) {
  set_has_pid();
  pid_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:mesos.internal.AuthenticateMessage.pid)
}
inline ::std::string* AuthenticateMessage::mutable_pid() {
  set_has_pid();
  // @@protoc_insertion_point(field_mutable:mesos.internal.AuthenticateMessage.pid)
  return pid_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* AuthenticateMessage::release_pid() {
  // @@protoc_insertion_point(field_release:mesos.internal.AuthenticateMessage.pid)
  clear_has_pid();
  return pid_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void AuthenticateMessage::set_allocated_pid(::std::string* pid) {
  if (pid != NULL) {
    set_has_pid();
  } else {
    clear_has_pid();
  }
  pid_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pid,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:mesos.internal.AuthenticateMessage.pid)
}
inline ::std::string* AuthenticateMessage::unsafe_arena_release_pid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mesos.internal.AuthenticateMessage.pid)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  clear_has_pid();
  return pid_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void AuthenticateMessage::unsafe_arena_set_allocated_pid(
    ::std::string* pid) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (pid != NULL) {
    set_has_pid();
  } else {
    clear_has_pid();
  }
  pid_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      pid, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mesos.internal.AuthenticateMessage.pid)
}

// -------------------------------------------------------------------

// AuthenticationMechanismsMessage

// repeated string mechanisms = 1;
inline int AuthenticationMechanismsMessage::mechanisms_size() const {
  return mechanisms_.size();
}
inline void AuthenticationMechanismsMessage::clear_mechanisms() {
  mechanisms_.Clear();
}
inline const ::std::string& AuthenticationMechanismsMessage::mechanisms(int index) const {
  // @@protoc_insertion_point(field_get:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  return mechanisms_.Get(index);
}
inline ::std::string* AuthenticationMechanismsMessage::mutable_mechanisms(int index) {
  // @@protoc_insertion_point(field_mutable:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  return mechanisms_.Mutable(index);
}
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  mechanisms_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  mechanisms_.Mutable(index)->assign(std::move(value));
}
#endif
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  mechanisms_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
}
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, const char* value, size_t size) {
  mechanisms_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
}
inline ::std::string* AuthenticationMechanismsMessage::add_mechanisms() {
  // @@protoc_insertion_point(field_add_mutable:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  return mechanisms_.Add();
}
inline void AuthenticationMechanismsMessage::add_mechanisms(const ::std::string& value) {
  mechanisms_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
}
#if LANG_CXX11
inline void AuthenticationMechanismsMessage::add_mechanisms(::std::string&& value) {
  mechanisms_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
}
#endif
inline void AuthenticationMechanismsMessage::add_mechanisms(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  mechanisms_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
}
inline void AuthenticationMechanismsMessage::add_mechanisms(const char* value, size_t size) {
  mechanisms_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AuthenticationMechanismsMessage::mechanisms() const {
  // @@protoc_insertion_point(field_list:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  return mechanisms_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AuthenticationMechanismsMessage::mutable_mechanisms() {
  // @@protoc_insertion_point(field_mutable_list:mesos.internal.AuthenticationMechanismsMessage.mechanisms)
  return &mechanisms_;
}

// -------------------------------------------------------------------

// AuthenticationStartMessage

// required string mechanism = 1;
inline bool AuthenticationStartMessage::has_mechanism() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationStartMessage::set_has_mechanism() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationStartMessage::clear_has_mechanism() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationStartMessage::clear_mechanism() {
  mechanism_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  clear_has_mechanism();
}
inline const ::std::string& AuthenticationStartMessage::mechanism() const {
  // @@protoc_insertion_point(field_get:mesos.internal.AuthenticationStartMessage.mechanism)
  return mechanism_.Get();
}
inline void AuthenticationStartMessage::set_mechanism(const ::std::string& value) {
  set_has_mechanism();
  mechanism_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticationStartMessage.mechanism)
}
#if LANG_CXX11
inline void AuthenticationStartMessage::set_mechanism(::std::string&& value) {
  set_has_mechanism();
  mechanism_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:mesos.internal.AuthenticationStartMessage.mechanism)
}
#endif
inline void AuthenticationStartMessage::set_mechanism(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_mechanism();
  mechanism_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:mesos.internal.AuthenticationStartMessage.mechanism)
}
inline void AuthenticationStartMessage::set_mechanism(const char* value,
    size_t size) {
  set_has_mechanism();
  mechanism_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:mesos.internal.AuthenticationStartMessage.mechanism)
}
inline ::std::string* AuthenticationStartMessage::mutable_mechanism() {
  set_has_mechanism();
  // @@protoc_insertion_point(field_mutable:mesos.internal.AuthenticationStartMessage.mechanism)
  return mechanism_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* AuthenticationStartMessage::release_mechanism() {
  // @@protoc_insertion_point(field_release:mesos.internal.AuthenticationStartMessage.mechanism)
  clear_has_mechanism();
  return mechanism_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void AuthenticationStartMessage::set_allocated_mechanism(::std::string* mechanism) {
  if (mechanism != NULL) {
    set_has_mechanism();
  } else {
    clear_has_mechanism();
  }
  mechanism_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mechanism,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:mesos.internal.AuthenticationStartMessage.mechanism)
}
inline ::std::string* AuthenticationStartMessage::unsafe_arena_release_mechanism() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mesos.internal.AuthenticationStartMessage.mechanism)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  clear_has_mechanism();
  return mechanism_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void AuthenticationStartMessage::unsafe_arena_set_allocated_mechanism(
    ::std::string* mechanism) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (mechanism != NULL) {
    set_has_mechanism();
  } else {
    clear_has_mechanism();
  }
  mechanism_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      mechanism, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mesos.internal.AuthenticationStartMessage.mechanism)
}

// optional bytes data = 2;
inline bool AuthenticationStartMessage::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AuthenticationStartMessage::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AuthenticationStartMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AuthenticationStartMessage::clear_data() {
  data_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  clear_has_data();
}
inline const ::std::string& AuthenticationStartMessage::data() const {
  // @@protoc_insertion_point(field_get:mesos.internal.AuthenticationStartMessage.data)
  return data_.Get();
}
inline void AuthenticationStartMessage::set_data(const ::std::string& value) {
  set_has_data();
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticationStartMessage.data)
}
#if LANG_CXX11
inline void AuthenticationStartMessage::set_data(::std::string&& value) {
  set_has_data();
  data_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:mesos.internal.AuthenticationStartMessage.data)
}
#endif
inline void AuthenticationStartMessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data();
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:mesos.internal.AuthenticationStartMessage.data)
}
inline void AuthenticationStartMessage::set_data(const void* value,
    size_t size) {
  set_has_data();
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:mesos.internal.AuthenticationStartMessage.data)
}
inline ::std::string* AuthenticationStartMessage::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:mesos.internal.AuthenticationStartMessage.data)
  return data_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* AuthenticationStartMessage::release_data() {
  // @@protoc_insertion_point(field_release:mesos.internal.AuthenticationStartMessage.data)
  clear_has_data();
  return data_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void AuthenticationStartMessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:mesos.internal.AuthenticationStartMessage.data)
}
inline ::std::string* AuthenticationStartMessage::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mesos.internal.AuthenticationStartMessage.data)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  clear_has_data();
  return data_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void AuthenticationStartMessage::unsafe_arena_set_allocated_data(
    ::std::string* data) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      data, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mesos.internal.AuthenticationStartMessage.data)
}

// -------------------------------------------------------------------

// AuthenticationStepMessage

// required bytes data = 1;
inline bool AuthenticationStepMessage::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationStepMessage::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationStepMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationStepMessage::clear_data() {
  data_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  clear_has_data();
}
inline const ::std::string& AuthenticationStepMessage::data() const {
  // @@protoc_insertion_point(field_get:mesos.internal.AuthenticationStepMessage.data)
  return data_.Get();
}
inline void AuthenticationStepMessage::set_data(const ::std::string& value) {
  set_has_data();
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticationStepMessage.data)
}
#if LANG_CXX11
inline void AuthenticationStepMessage::set_data(::std::string&& value) {
  set_has_data();
  data_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:mesos.internal.AuthenticationStepMessage.data)
}
#endif
inline void AuthenticationStepMessage::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data();
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:mesos.internal.AuthenticationStepMessage.data)
}
inline void AuthenticationStepMessage::set_data(const void* value,
    size_t size) {
  set_has_data();
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:mesos.internal.AuthenticationStepMessage.data)
}
inline ::std::string* AuthenticationStepMessage::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:mesos.internal.AuthenticationStepMessage.data)
  return data_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* AuthenticationStepMessage::release_data() {
  // @@protoc_insertion_point(field_release:mesos.internal.AuthenticationStepMessage.data)
  clear_has_data();
  return data_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void AuthenticationStepMessage::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:mesos.internal.AuthenticationStepMessage.data)
}
inline ::std::string* AuthenticationStepMessage::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mesos.internal.AuthenticationStepMessage.data)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  clear_has_data();
  return data_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void AuthenticationStepMessage::unsafe_arena_set_allocated_data(
    ::std::string* data) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      data, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mesos.internal.AuthenticationStepMessage.data)
}

// -------------------------------------------------------------------

// AuthenticationCompletedMessage

// -------------------------------------------------------------------

// AuthenticationFailedMessage

// -------------------------------------------------------------------

// AuthenticationErrorMessage

// optional string error = 1;
inline bool AuthenticationErrorMessage::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationErrorMessage::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationErrorMessage::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationErrorMessage::clear_error() {
  error_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  clear_has_error();
}
inline const ::std::string& AuthenticationErrorMessage::error() const {
  // @@protoc_insertion_point(field_get:mesos.internal.AuthenticationErrorMessage.error)
  return error_.Get();
}
inline void AuthenticationErrorMessage::set_error(const ::std::string& value) {
  set_has_error();
  error_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:mesos.internal.AuthenticationErrorMessage.error)
}
#if LANG_CXX11
inline void AuthenticationErrorMessage::set_error(::std::string&& value) {
  set_has_error();
  error_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:mesos.internal.AuthenticationErrorMessage.error)
}
#endif
inline void AuthenticationErrorMessage::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_error();
  error_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:mesos.internal.AuthenticationErrorMessage.error)
}
inline void AuthenticationErrorMessage::set_error(const char* value,
    size_t size) {
  set_has_error();
  error_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:mesos.internal.AuthenticationErrorMessage.error)
}
inline ::std::string* AuthenticationErrorMessage::mutable_error() {
  set_has_error();
  // @@protoc_insertion_point(field_mutable:mesos.internal.AuthenticationErrorMessage.error)
  return error_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* AuthenticationErrorMessage::release_error() {
  // @@protoc_insertion_point(field_release:mesos.internal.AuthenticationErrorMessage.error)
  clear_has_error();
  return error_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void AuthenticationErrorMessage::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:mesos.internal.AuthenticationErrorMessage.error)
}
inline ::std::string* AuthenticationErrorMessage::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:mesos.internal.AuthenticationErrorMessage.error)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  clear_has_error();
  return error_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void AuthenticationErrorMessage::unsafe_arena_set_allocated_error(
    ::std::string* error) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (error != NULL) {
    set_has_error();
  } else {
    clear_has_error();
  }
  error_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      error, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mesos.internal.AuthenticationErrorMessage.error)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace internal
}  // namespace mesos

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mesos_2fauthentication_2fauthentication_2eproto__INCLUDED
